//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankTransactions
{
    using System;
    using System.Collections.Generic;
    
    public partial class Operation
    {
        public int ID { get; set; }
        public string DateOperation { get; set; }
        public Nullable<int> Client_ID { get; set; }
        public Nullable<int> Paymaster_ID { get; set; }
        public string Processing_Stage { get; set; }
        public string Type { get; set; }
        public Nullable<decimal> Amount { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Paymaster Paymaster { get; set; }
    }
}
